version: "3.6"

services:
  db:
    image: postgres:13
    restart: always
    container_name: todolist-db
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    env_file:
      - ./.env_db
    volumes:
      - ./db:/var/lib/postgresql/data
