version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    depends_on:
#      - db
    container_name: todolist-app
    env_file:
      - ./.env_app
    volumes:
      - ./logs:/var/log/container
    ports:
      - 80:8000
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M


#  db:
#    image: postgres:13
#    restart: always
#    container_name: todolist-db
#    ports:
#      - 5432:5432
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 50M
#    env_file:
#      - ./.env_db
#    volumes:
#      - ./db:/var/lib/postgresql/data

#  rabbit:
#    image: rabbitmq:3.10.7-management
#    container_name: rabbit_mq
#    hostname: localhost
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - 15672:15672
#      - 5672:5672

#  receiver:
#    image: receiver
#    container_name: rabbit_receiver
#    restart: always
#    depends_on:
#      - rabbit