version: "3.6"

services:
  web1:
    build:
      context: .
      dockerfile: ./Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn MyToDoList.wsgi:application --bind 0.0.0.0:8000
    container_name: todolist-app-1
    env_file:
      - ./.env_app
    volumes:
      - ./logs:/var/log/container
    ports:
      - 8001:8000
#    network_mode: "host"
#    expose:
#      - 8001
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M


  web2:
    build:
      context: .
      dockerfile: ./Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn MyToDoList.wsgi:application --bind 0.0.0.0:8000
    container_name: todolist-app-2
    env_file:
      - ./.env_app
    volumes:
      - ./logs:/var/log/container
    ports:
      - 8002:8000
#    network_mode: "host"
#    expose:
#      - 8002
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M


  load_balancer:
    image: nginx
    container_name: load_balancer
    volumes:
      - ./nginx/conf_lb:/etc/nginx/conf.d
    ports:
      - 1234:80
#    network_mode: "host"
    depends_on: 
      - web1
      - web2

  db:
    image: postgres:13
    restart: always
    container_name: todolist-db
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    env_file:
      - ./.env_db
    volumes:
      - ./db:/var/lib/postgresql/data

#  rabbit:
#    image: rabbitmq:3.10.7-management
#    container_name: rabbit_mq
#    hostname: localhost
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - 15672:15672
#      - 5672:5672

#  receiver:
#    image: receiver
#    container_name: rabbit_receiver
#    restart: always
#    depends_on:
#      - rabbit