# Generated by Django 4.0.3 on 2022-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static/ToDo/images/default.png', upload_to='images/', verbose_name='Avatar'),
        ),
    ]
