# Generated by Django 4.0.3 on 2022-03-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_alter_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
