# Generated by Django 4.0.3 on 2022-03-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0007_rename_user_id_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
