version: "3.6"

services:
  db:
#    image: postgres:13
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: todolist-db
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
    env_file:
      - ./.env_db
    volumes:
      - ./db:/var/lib/postgresql/data
      - /var/log/container/postgresql:/logs
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
